name: 'playground'
description: 'playground'
inputs:
  title:
    description: title
    required: true
  service:
    description: service
    required: true
  apikey:
    description: apikey
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist-post/index.js'

