name: 'playground'
description: 'playground'
inputs:
  token:
    description: 'github token'
    required: true
  mode:
    description: 'start/finish'
    required: true
  debug_context:
    description: debug
    required: false
  debug_chdir:
    description: debug
    required: false
outputs:
  time: # output will be available to future steps
    description: 'The message to output'
runs:
  using: 'node12'
  main: 'dist/index.js'
