name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
      - 'test*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
# test:
#   runs-on: ubuntu-latest
#   steps:
#   - uses: actions/checkout@v2
#   - uses: ./
#     id: start
#     with:
#       mode: start

#   - run: ./test.bash
#     env:
#       DATA1: ${{ steps.start.outputs.data1 }}
#       DATA2: ${{ steps.start.outputs.data2 }}

