name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      args:
        description: 'args'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        title: test
        service: hobby
        apikey: ${{ secrets.apikey }}

    - run: sleep 10

